// components.js — Battery-pack component & materials database for the 3D pack designer.
//
// All numeric properties are CLASS-TYPICAL MARKET VALUES intended for first-order
// design and visualization, not datasheet values for a specific SKU. Listed
// suppliers are REPRESENTATIVE EXAMPLES of companies active in each product
// class, NOT endorsements or a statement of fitness for purpose. Always verify
// against a real datasheet before committing a design.
//
// Plain ES module, no imports. Every component carries the common fields
// { id, name, kind, forms, suppliers, notes, dataQuality } plus
// category-specific fields; fields that are truly not applicable are null.

export const COMPONENT_CATEGORIES = [
  { key: 'busbar', name: 'Busbar / interconnect' },
  { key: 'spacer', name: 'Cell spacer / holder' },
  { key: 'vent', name: 'Venting / gas management' },
  { key: 'cooling', name: 'Cooling system' },
  { key: 'tim', name: 'Thermal interface material' },
  { key: 'housing', name: 'Housing / enclosure' },
];

export const COMPONENTS = {
  // ---------------------------------------------------------------- busbar --
  busbar: [
    {
      id: 'nickel-strip-0p15',
      name: 'Pure nickel strip, 0.15 mm (spot-welded)',
      kind: 'nickel-strip',
      forms: ['cylindrical'],
      suppliers: ['Ametek Specialty Metal Products', 'Targray'],
      notes: 'Workhorse interconnect for spot-welded 18650/21700 packs; 0.15 x 7 mm strip is easy to weld with hobby and production resistance welders. Keep continuous current to a conservative ~5 A per cell joint or parallel multiple strips to limit I2R heating.',
      dataQuality: 'typical-class',
      material: 'nickel',
      crossSectionMm2: 1.05,
      ampacityAPerJoint: 5,
      resistivityNOhmM: 69,
      joinMethod: 'spot-weld',
      massGPerCell: 1.5,
    },
    {
      id: 'nickel-strip-0p2',
      name: 'Pure nickel strip, 0.20 mm (spot-welded)',
      kind: 'nickel-strip',
      forms: ['cylindrical'],
      suppliers: ['Ametek Specialty Metal Products', 'Targray'],
      notes: 'Heavier 0.20 x 8 mm nickel strip for higher-current e-bike/e-moto packs; needs a more capable welder (higher energy pulses) than 0.15 mm stock. Roughly ~7 A conservative continuous per joint; double-layer welds are common for power packs.',
      dataQuality: 'typical-class',
      material: 'nickel',
      crossSectionMm2: 1.6,
      ampacityAPerJoint: 7,
      resistivityNOhmM: 69,
      joinMethod: 'spot-weld',
      massGPerCell: 2.4,
    },
    {
      id: 'nickel-plated-steel-strip',
      name: 'Nickel-plated steel strip (budget)',
      kind: 'plated-steel-strip',
      forms: ['cylindrical'],
      suppliers: ['Toyo Kohan', 'commodity strip importers'],
      notes: 'Budget alternative to pure nickel with roughly 2x the resistivity, so it runs hotter at the same current — derate to ~3 A per joint and reserve for low-power packs. Welds easily but plating quality varies; watch for corrosion at weld splatter sites.',
      dataQuality: 'typical-class',
      material: 'nickel-plated-steel',
      crossSectionMm2: 1.05,
      ampacityAPerJoint: 3,
      resistivityNOhmM: 130,
      joinMethod: 'spot-weld',
      massGPerCell: 1.5,
    },
    {
      id: 'copper-busbar-laser',
      name: 'Copper collector busbar, laser-welded',
      kind: 'copper-busbar',
      forms: ['cylindrical'],
      suppliers: ['Wieland', 'Aurubis'],
      notes: 'Nickel- or tin-plated copper collector plate laser-welded to cell caps/cans, the EV-grade solution for high-current cylindrical modules. Copper’s low resistivity supports ~15 A conservative continuous per joint, but laser welding to cell hardware requires tight process control.',
      dataQuality: 'typical-class',
      material: 'copper',
      crossSectionMm2: 4.0,
      ampacityAPerJoint: 15,
      resistivityNOhmM: 17,
      joinMethod: 'laser-weld',
      massGPerCell: 4.0,
    },
    {
      id: 'stamped-aluminum-busbar',
      name: 'Stamped aluminum busbar (prismatic module)',
      kind: 'stamped-busbar',
      forms: ['prismatic'],
      suppliers: ['Interplex', 'Wieland e.mobility', 'Jonver Electronics'],
      notes: 'Thick stamped EN AW-1050/3003 busbars laser-welded (or bolted on serviceable designs) across prismatic terminals; the norm in EV and ESS prismatic modules. Sized generously — ~60 mm2 supports ~200 A conservative continuous per terminal joint with modest temperature rise.',
      dataQuality: 'typical-class',
      material: 'aluminum',
      crossSectionMm2: 60,
      ampacityAPerJoint: 200,
      resistivityNOhmM: 27,
      joinMethod: 'laser-weld',
      massGPerCell: 45,
    },
    {
      id: 'aluminum-wire-bond',
      name: 'Ultrasonic aluminum wire bonds (~0.38 mm)',
      kind: 'wire-bond',
      forms: ['cylindrical'],
      suppliers: ['F&K Delvotec', 'Hesse Mechatronics'],
      notes: 'Tesla-style ~0.38 mm aluminum wire ultrasonically bonded from each cell to a collector plate; each bond deliberately acts as a per-cell fuse, isolating a shorted cell from the parallel group. Conservative continuous rating ~8 A per bond; fusing occurs well above that. Mass shown is the wire only — the aluminum collector plate is additional.',
      dataQuality: 'typical-class',
      material: 'aluminum',
      crossSectionMm2: 0.11,
      ampacityAPerJoint: 8,
      resistivityNOhmM: 27,
      joinMethod: 'ultrasonic-wire-bond',
      massGPerCell: 0.2,
    },
    {
      id: 'braided-copper-link',
      name: 'Flexible braided copper link (module-to-module)',
      kind: 'braided-link',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Mersen', 'nVent ERIFLEX'],
      notes: 'Bolted flexible braided/laminated copper links between modules absorb tolerance stack-up, vibration and thermal expansion that rigid bars would transmit into terminals. ~25 mm2 braid carries ~150 A conservatively; mass shown is amortized per cell at module level.',
      dataQuality: 'typical-class',
      material: 'copper',
      crossSectionMm2: 25,
      ampacityAPerJoint: 150,
      resistivityNOhmM: 17,
      joinMethod: 'bolted',
      massGPerCell: 3,
    },
    {
      id: 'ccs-cell-contact-system',
      name: 'Cell contact system (CCS, plastic carrier)',
      kind: 'cell-contact-system',
      forms: ['cylindrical', 'prismatic'],
      suppliers: ['Diehl Advanced Mobility', 'Interplex', 'Jonver Electronics'],
      notes: 'Integrated plastic-carrier assembly with laser-welded aluminum interconnects plus voltage-sense (and often temperature-sense) flex circuits routed to a single BMS connector — the modern OEM approach that removes hand wiring. Per-joint rating ~12 A conservative for cylindrical variants; carrier adds mass but drops assembly cost at volume.',
      dataQuality: 'typical-class',
      material: 'aluminum',
      crossSectionMm2: 3.0,
      ampacityAPerJoint: 12,
      resistivityNOhmM: 27,
      joinMethod: 'laser-weld',
      massGPerCell: 6,
    },
    {
      id: 'pouch-tab-icb',
      name: 'Pouch tab interconnect board (laser-welded)',
      kind: 'tab-interconnect',
      forms: ['pouch'],
      suppliers: ['Amphenol', 'Interplex', 'Jonver Electronics'],
      notes: 'Interconnect board with plated copper busbars laser-welded directly to folded pouch tabs, with integrated sense lines; the standard pouch-module architecture. Wide thin tab welds give large contact area — ~100 A conservative continuous per cell joint is typical for EV-class pouch cells.',
      dataQuality: 'typical-class',
      material: 'copper',
      crossSectionMm2: 15,
      ampacityAPerJoint: 100,
      resistivityNOhmM: 17,
      joinMethod: 'laser-weld',
      massGPerCell: 25,
    },
  ],

  // ---------------------------------------------------------------- spacer --
  spacer: [
    {
      id: 'pp-honeycomb-holder',
      name: 'Molded PP honeycomb cell holder (18650/21700)',
      kind: 'molded-holder',
      forms: ['cylindrical'],
      suppliers: ['Keystone Electronics', 'custom injection molders'],
      notes: 'Injection-molded polypropylene matrix that fixes cell pitch, creates a ~2 mm air gap for cooling/propagation margin, and gives the stack rigidity; specify a UL94 V-0 grade for anything beyond hobby use. Standard top+bottom holder pairs for 18650 and 21700 pitches are commodity items.',
      dataQuality: 'typical-class',
      providesGapMm: 2,
      thermalBarrier: false,
      thermalCondWmK: 0.2,
      flameRating: 'UL94 V-0',
      massGPerCell: 4,
    },
    {
      id: 'snap-holder-bricks',
      name: 'Snap-together holder bricks (hobby class)',
      kind: 'snap-holder',
      forms: ['cylindrical'],
      suppliers: ['Vruzend', 'commodity importers'],
      notes: 'Interlocking ABS bricks that snap around individual cells for arbitrary pack shapes; convenient for prototyping but most are unrated for flammability and add more gap and mass than molded holders. Verify the resin rating before using in an enclosed pack.',
      dataQuality: 'typical-class',
      providesGapMm: 2.5,
      thermalBarrier: false,
      thermalCondWmK: 0.17,
      flameRating: null,
      massGPerCell: 5,
    },
    {
      id: 'silicone-spacer-pad',
      name: 'Silicone spacer pad',
      kind: 'elastomer-pad',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Rogers (BISCO)', 'Saint-Gobain'],
      notes: 'Die-cut silicone pads (~1 mm) between or under cells provide vibration isolation, tolerance take-up, and mild electrical isolation; silicone grades are widely available in UL94 V-0. Not a meaningful thermal barrier — pair with aerogel or mica where propagation resistance is required.',
      dataQuality: 'typical-class',
      providesGapMm: 1,
      thermalBarrier: false,
      thermalCondWmK: 0.2,
      flameRating: 'UL94 V-0',
      massGPerCell: 3,
    },
    {
      id: 'aerogel-barrier-sheet',
      name: 'Aerogel thermal barrier sheet (PyroThin class)',
      kind: 'aerogel-sheet',
      forms: ['prismatic', 'pouch'],
      suppliers: ['Aspen Aerogels', 'Armacell'],
      notes: 'Silica-aerogel composite sheets (Aspen PyroThin class, ~0.02 W/mK) placed between cell faces are the current benchmark for cell-to-cell propagation resistance in prismatic and pouch stacks, holding barrier performance at 1-3 mm thickness even under compression. Also accommodates pouch swell when specified as a compressible grade.',
      dataQuality: 'typical-class',
      providesGapMm: 2,
      thermalBarrier: true,
      thermalCondWmK: 0.02,
      flameRating: 'UL94 V-0',
      massGPerCell: 8,
    },
    {
      id: 'mica-barrier-sheet',
      name: 'Mica barrier sheet',
      kind: 'mica-sheet',
      forms: ['prismatic', 'pouch'],
      suppliers: ['Von Roll', 'Elmelin'],
      notes: 'Rigid phlogopite/muscovite mica laminate withstands >1000 C flame impingement and is a low-cost, proven barrier between cells and as pack-lid lining; inorganic and non-combustible (UL94 not applicable). Higher conductivity than aerogel, so it blocks flame and hot ejecta more than steady-state heat.',
      dataQuality: 'typical-class',
      providesGapMm: 0.8,
      thermalBarrier: true,
      thermalCondWmK: 0.3,
      flameRating: null,
      massGPerCell: 10,
    },
    {
      id: 'compression-foam-pad',
      name: 'PU/silicone compression foam pad (pouch stack)',
      kind: 'compression-foam',
      forms: ['pouch'],
      suppliers: ['Rogers (PORON)', 'Saint-Gobain (Norseal)'],
      notes: 'Microcellular PU or silicone foam (1-3 mm) between pouch cells maintains stack preload across life as cells breathe and swell — required for pouch cycle life, with compression set the key selection parameter. V-0 grades are standard in EV programs.',
      dataQuality: 'typical-class',
      providesGapMm: 2,
      thermalBarrier: false,
      thermalCondWmK: 0.08,
      flameRating: 'UL94 V-0',
      massGPerCell: 6,
    },
    {
      id: 'ceramic-fiber-blanket',
      name: 'Ceramic-fiber blanket',
      kind: 'fiber-blanket',
      forms: ['prismatic', 'pouch'],
      suppliers: ['Morgan Advanced Materials', 'Alkegen (Unifrax)'],
      notes: 'Alumina-silicate fiber blanket (3-6 mm) used between cell groups and as enclosure lining in ESS; non-combustible with good high-temperature stability, but bulkier and dustier to handle than aerogel sheet. Compresses significantly, so retain it mechanically.',
      dataQuality: 'typical-class',
      providesGapMm: 4,
      thermalBarrier: true,
      thermalCondWmK: 0.06,
      flameRating: null,
      massGPerCell: 15,
    },
    {
      id: 'direct-bond-none',
      name: 'Direct bond, no spacer (structural adhesive)',
      kind: 'structural-bond',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Sika', 'Henkel'],
      notes: 'Cells bonded directly to each other or to the structure with structural polyurethane/epoxy adhesive at effectively zero gap — the cell-to-pack/structural-pack approach that maximizes packing density and stiffness. No thermal barrier between cells, so propagation mitigation must come from elsewhere (vent paths, coolant, barriers at group level).',
      dataQuality: 'typical-class',
      providesGapMm: null,
      thermalBarrier: false,
      thermalCondWmK: 0.4,
      flameRating: null,
      massGPerCell: 2,
    },
  ],

  // ------------------------------------------------------------------ vent --
  vent: [
    {
      id: 'cell-score-vent-cid',
      name: 'Integral score vent + CID (cylindrical cell)',
      kind: 'cell-integral-vent',
      forms: ['cylindrical'],
      suppliers: ['Panasonic', 'Samsung SDI'],
      notes: 'Built into every quality 18650/21700: the CID permanently opens the circuit at roughly 0.7-1.0 MPa internal pressure, and the scored header ruptures around 1.5-2.5 MPa to release gas axially. This entry is informational — you select it by choosing the cell — but the pack must still provide a path for the vented gas.',
      dataQuality: 'typical-class',
      level: 'cell',
      mechanism: 'score-vent-cid',
      activationNote: 'CID disconnect at ~0.7-1.0 MPa cell internal pressure; score vent bursts at ~1.5-2.5 MPa, venting through the positive cap.',
    },
    {
      id: 'prismatic-burst-disc',
      name: 'Integrated burst disc (prismatic cell lid)',
      kind: 'burst-disc',
      forms: ['prismatic'],
      suppliers: ['CATL', 'Samsung SDI'],
      notes: 'Laser-scored or welded-foil burst disc in the prismatic can lid opens at a calibrated pressure and defines the cell’s gas ejection point — orient modules so discs face the pack vent channel, never an adjacent cell. Cell-level and non-reclosing.',
      dataQuality: 'typical-class',
      level: 'cell',
      mechanism: 'burst-disc',
      activationNote: 'Non-reclosing; opens at ~0.4-0.8 MPa cell internal pressure and ejects gas at the disc location on the lid.',
    },
    {
      id: 'ptfe-breather-membrane',
      name: 'PTFE breather membrane vent (pack)',
      kind: 'breather-membrane',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['W. L. Gore', 'Donaldson'],
      notes: 'Screw-in or snap-in ePTFE element (Gore PolyVent class) that continuously equalizes barometric/thermal pressure differentials while blocking liquid water and dust, preserving IP67. Many variants add a burst function that opens a larger area during thermal-runaway overpressure.',
      dataQuality: 'typical-class',
      level: 'pack',
      mechanism: 'ptfe-membrane',
      activationNote: 'Always open to gas diffusion — equalizes normal pressure swings continuously; burst variants additionally open fully at ~10-30 kPa differential.',
    },
    {
      id: 'spring-prv',
      name: 'Spring-loaded pressure relief valve (pack)',
      kind: 'relief-valve',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Eaton', 'Oseco'],
      notes: 'Reclosing spring-poppet valve that cracks at a set gauge pressure to dump vent gas and then reseals, keeping the enclosure sealed against water ingress afterwards; common on ESS cabinets and larger EV packs alongside a breather membrane. Size the flow area for the worst-case multi-cell vent rate, not a single cell.',
      dataQuality: 'typical-class',
      level: 'pack',
      mechanism: 'spring-prv',
      activationNote: 'Cracks at ~5-20 kPa gauge enclosure pressure, reseals after the event; flow area must match expected gas generation rate.',
    },
    {
      id: 'ess-rupture-panel',
      name: 'Rupture panel (container-scale ESS)',
      kind: 'rupture-panel',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Fike', 'OsecoElfab'],
      notes: 'Large-area deflagration vent panel in the container wall or roof, sized per NFPA 68 to relieve a gas deflagration before the structure fails; standard on containerized ESS and battery rooms. One-shot device — panels are replaced after activation.',
      dataQuality: 'typical-class',
      level: 'pack',
      mechanism: 'rupture-panel',
      activationNote: 'Opens at low static overpressure (~2-10 kPa, per NFPA 68 sizing) to relieve deflagration pressure; non-reclosing.',
    },
    {
      id: 'directional-vent-duct',
      name: 'Directional vent duct / channel',
      kind: 'vent-duct',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Boyd', 'custom sheet-metal fabricators'],
      notes: 'Dedicated mica- or steel-lined channel that captures gas from cell vent locations and routes it to the pack exit, keeping >600 C ejecta off neighboring cells, busbars and harnesses. The duct exit is typically closed by a foil or film cover that bursts at low pressure.',
      dataQuality: 'typical-class',
      level: 'pack',
      mechanism: 'rupture-panel',
      activationNote: 'Passive channel from cell vents to the pack exit; foil/film exit cover bursts at low differential pressure (~5-20 kPa) during a vent event.',
    },
  ],

  // --------------------------------------------------------------- cooling --
  cooling: [
    {
      id: 'passive-air',
      name: 'Passive natural convection',
      kind: 'natural-convection',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: null,
      notes: 'No cooling hardware — heat leaves through the enclosure by natural convection and radiation, with effective HTC of only ~5-10 W/m2K to ambient. Adequate for low-C-rate packs (<~0.5C continuous) with generous surface area; thermal mass rides through short bursts.',
      dataQuality: 'typical-class',
      placement: 'air',
      htcWm2K: [5, 10],
      massKgPerM2: null,
      needsPump: false,
      viz: null,
    },
    {
      id: 'forced-air',
      name: 'Forced-air fan + ducts',
      kind: 'forced-air',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['ebm-papst', 'Delta Electronics'],
      notes: 'Fans and ducting drive air through cell gaps for ~25-60 W/m2K effective HTC; cheap and simple but limited by air’s heat capacity, causing inlet-to-outlet cell temperature gradients at high power. Filter or seal against dust in dirty environments — the airflow path breaks IP sealing.',
      dataQuality: 'typical-class',
      placement: 'air',
      htcWm2K: [25, 60],
      massKgPerM2: null,
      needsPump: false,
      viz: null,
    },
    {
      id: 'bottom-cold-plate',
      name: 'Bottom liquid cold plate',
      kind: 'cold-plate',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Dana', 'Modine'],
      notes: 'Brazed or stamped aluminum plate with glycol coolant channels under the cells — the EV prismatic norm, also used under cylindrical and pouch cell-to-pack layouts. Delivers ~300-1000 W/m2K at the plate; overall performance hinges on the TIM layer between cell base and plate.',
      dataQuality: 'typical-class',
      placement: 'bottom',
      htcWm2K: [300, 1000],
      massKgPerM2: 8,
      needsPump: true,
      viz: 'bottom',
    },
    {
      id: 'side-cold-plates',
      name: 'Side cold plates',
      kind: 'cold-plate',
      forms: ['prismatic', 'pouch'],
      suppliers: ['Mahle', 'Valeo'],
      notes: 'Liquid plates against the large faces or module side walls pull heat through the cells’ best in-plane conduction path, giving lower cell-internal gradients than bottom-only cooling for tall prismatic and pouch formats. Costs pack width and requires compliant TIM to handle tolerance and swell.',
      dataQuality: 'typical-class',
      placement: 'side',
      htcWm2K: [300, 800],
      massKgPerM2: 6,
      needsPump: true,
      viz: 'side',
    },
    {
      id: 'serpentine-ribbon',
      name: 'Between-cell serpentine cooling ribbon',
      kind: 'cooling-ribbon',
      forms: ['cylindrical'],
      suppliers: ['Tesla (in-house archetype)', 'Dana'],
      notes: 'Tesla-style flattened aluminum ribbon snaking between cylindrical cell rows, bonded to each can with thermally conductive adhesive; cools the cell side wall directly for ~200-600 W/m2K effective contact. Excellent temperature uniformity, but the wetted ribbon is a single glycol circuit threading the whole module.',
      dataQuality: 'typical-class',
      placement: 'between',
      htcWm2K: [200, 600],
      massKgPerM2: 2.5,
      needsPump: true,
      viz: 'between',
    },
    {
      id: 'pouch-fin-plates',
      name: 'Between-cell fin plates (pouch)',
      kind: 'fin-plate',
      forms: ['pouch'],
      suppliers: ['LG Energy Solution (module archetype)', 'Boyd'],
      notes: 'Thin aluminum fins interleaved between pouch cells conduct face heat down to an edge or base cold plate — the classic pouch-module architecture (GM/LG heritage). Effective ~200-600 W/m2K at the cell face while keeping coolant out of the cell stack.',
      dataQuality: 'typical-class',
      placement: 'between',
      htcWm2K: [200, 600],
      massKgPerM2: 2.7,
      needsPump: true,
      viz: 'between',
    },
    {
      id: 'dielectric-immersion',
      name: 'Dielectric immersion cooling',
      kind: 'immersion',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['M&I Materials (MIVOLT)', 'Shell'],
      notes: 'Cells fully or partially submerged in circulating dielectric fluid for ~500-1500 W/m2K over the entire wetted surface — the highest-performance option, strong for fast-charge and propagation suppression. Penalties are fluid mass, sealing, and serviceability; still niche in production.',
      dataQuality: 'typical-class',
      placement: 'immersion',
      htcWm2K: [500, 1500],
      massKgPerM2: null,
      needsPump: true,
      viz: null,
    },
    {
      id: 'pcm-graphite',
      name: 'PCM + graphite composite matrix',
      kind: 'pcm-composite',
      forms: ['cylindrical'],
      suppliers: ['Beam Global (AllCell)', 'Rubitherm'],
      notes: 'Wax phase-change material in a graphite matrix molded around cylindrical cells absorbs burst heat by melting (~40-50 C) and spreads it laterally; a passive buffer, not steady-state cooling — the modest effective HTC shown reflects heat still exiting via the enclosure. Best for duty cycles with recovery time between peaks.',
      dataQuality: 'typical-class',
      placement: 'between',
      htcWm2K: [10, 30],
      massKgPerM2: null,
      needsPump: false,
      viz: 'between',
    },
  ],

  // ------------------------------------------------------------------- tim --
  tim: [
    {
      id: 'none-dry',
      name: 'None / dry contact',
      kind: 'dry-contact',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: null,
      notes: 'Bare metal-to-metal contact leaves microscopic air gaps, and air at ~0.03 W/mK dominates the joint — expect an order of magnitude more thermal resistance than any real TIM. Acceptable only where the cooling path is not thermally critical.',
      dataQuality: 'typical-class',
      thermalCondWmK: 0.03,
      thicknessMm: [0.05, 0.2],
      dielectricKVPerMm: 3,
      densityKgM3: null,
    },
    {
      id: 'silicone-gap-pad',
      name: 'Silicone gap pad (1.5-3 W/mK class)',
      kind: 'gap-pad',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Henkel (Bergquist)', '3M', 'Fujipoly'],
      notes: 'Die-cut conformable silicone pads (Bergquist/3M/Fujipoly class, 1.5-3 W/mK) between cells or modules and cold plates; easy to assemble and rework, with good dielectric isolation. Requires 10-30% compression for rated performance, so account for the clamping load on cells.',
      dataQuality: 'typical-class',
      thermalCondWmK: 2.0,
      thicknessMm: [0.5, 3],
      dielectricKVPerMm: 10,
      densityKgM3: 2600,
    },
    {
      id: 'dispensable-gap-filler',
      name: 'Dispensable gap filler (2-4 W/mK class)',
      kind: 'gap-filler',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Henkel (Loctite)', 'Dow', 'Parker Lord'],
      notes: 'Two-part cure-in-place silicone or PU filler (Loctite/Dowsil class, 2-4 W/mK) robot-dispensed onto the cold plate before cell drop — the volume-production EV standard because it fills tolerance stack-up with near-zero assembly stress. Abrasive filler wear on dispensing equipment and cost per liter are the practical drawbacks.',
      dataQuality: 'typical-class',
      thermalCondWmK: 3.0,
      thicknessMm: [0.5, 3],
      dielectricKVPerMm: 8,
      densityKgM3: 2900,
    },
    {
      id: 'thermal-grease',
      name: 'Thermal grease',
      kind: 'grease',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Dow (Dowsil)', 'Shin-Etsu'],
      notes: 'Thin silicone grease gives the lowest interface resistance per millimeter at bond lines under ~0.2 mm, but it cannot bridge real gaps, can pump out under thermal cycling, and offers no rated dielectric isolation. Better suited to electronics-to-heatsink joints than cell-to-plate interfaces.',
      dataQuality: 'typical-class',
      thermalCondWmK: 2.0,
      thicknessMm: [0.05, 0.2],
      dielectricKVPerMm: null,
      densityKgM3: 2500,
    },
    {
      id: 'thermal-epoxy',
      name: 'Thermally conductive epoxy adhesive',
      kind: 'adhesive',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Master Bond', 'Henkel'],
      notes: 'Filled epoxy (~1-2 W/mK) that is both the thermal path and a structural bond — used to glue cells to ribbons, fins, or plates permanently. Rigid once cured: no rework, and CTE mismatch stresses must be checked over the temperature range.',
      dataQuality: 'typical-class',
      thermalCondWmK: 1.5,
      thicknessMm: [0.1, 0.5],
      dielectricKVPerMm: 15,
      densityKgM3: 1900,
    },
    {
      id: 'potting-compound',
      name: 'Potting compound (0.8-1.5 W/mK)',
      kind: 'potting',
      forms: ['cylindrical', 'pouch'],
      suppliers: ['Wacker', 'Elantas'],
      notes: 'PU or silicone potting poured around the whole cell array serves triple duty: TIM, vibration-proof structure, and ingress sealing, at a modest 0.8-1.5 W/mK. Adds significant mass and makes the pack unserviceable, so it suits small rugged packs rather than large ones.',
      dataQuality: 'typical-class',
      thermalCondWmK: 1.0,
      thicknessMm: [2, 10],
      dielectricKVPerMm: 12,
      densityKgM3: 1450,
    },
  ],

  // --------------------------------------------------------------- housing --
  housing: [
    {
      id: 'folded-aluminum-sheet',
      name: 'Folded/riveted sheet aluminum enclosure',
      kind: 'sheet-metal',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Protocase', 'regional sheet-metal fabricators'],
      notes: 'CNC-cut, folded and riveted (or pulse-welded) 1.5-3 mm 5052-class aluminum sheet — the default low-tooling enclosure for prototypes and light-industrial packs. Achieves IP54 with gaskets at joints and glands; welded seams are needed to go higher.',
      dataQuality: 'typical-class',
      material: 'aluminum-sheet',
      densityKgM3: 2700,
      flameRating: null,
      ipClass: 'IP54',
    },
    {
      id: 'extruded-aluminum-enclosure',
      name: 'Extruded aluminum enclosure with end caps',
      kind: 'extrusion',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Hydro Extrusions', 'Constellium'],
      notes: 'A 6xxx-series extruded profile forms the body in one piece — often with integral cooling channels and mounting rails — closed by machined or cast end caps with O-ring gaskets, reaching IP67. Per-part cost is excellent at volume; the constraint is a constant cross-section and die tooling lead time.',
      dataQuality: 'typical-class',
      material: 'aluminum-extrusion',
      densityKgM3: 2700,
      flameRating: null,
      ipClass: 'IP67',
    },
    {
      id: 'welded-steel-cabinet',
      name: 'Welded steel enclosure (ESS)',
      kind: 'welded-steel',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Rittal', 'regional weld shops'],
      notes: 'MIG/laser-welded 1.5-3 mm powder-coated steel — the ESS cabinet and rack standard where mass is unimportant and fire containment, stiffness, and low cost dominate. Steel’s high melting point buys meaningful thermal-runaway containment time versus aluminum.',
      dataQuality: 'typical-class',
      material: 'steel',
      densityKgM3: 7850,
      flameRating: null,
      ipClass: 'IP54',
    },
    {
      id: 'molded-fr-plastic',
      name: 'Molded FR ABS/PC enclosure (UL94 V-0)',
      kind: 'molded-plastic',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['Polycase', 'custom injection molders'],
      notes: 'Injection-molded flame-retardant ABS/PC in UL94 V-0 grades — the consumer and e-mobility norm (power tools, e-bikes) for its low mass, integrated snap features, and zero corrosion. Gasketed clamshells reach IP54-IP67; tooling cost only pays off at volume, and creep limits sustained clamping loads.',
      dataQuality: 'typical-class',
      material: 'plastic-v0',
      densityKgM3: 1200,
      flameRating: 'UL94 V-0',
      ipClass: 'IP54',
    },
    {
      id: 'potted-plastic-pack',
      name: 'Potted plastic pack (fully encapsulated)',
      kind: 'potted-assembly',
      forms: ['cylindrical', 'pouch'],
      suppliers: ['Wacker (potting)', 'Elantas (potting)'],
      notes: 'A thin molded shell used as a mold, then flooded with PU/silicone potting so the electronics and cells are fully encapsulated — effectively vibration-proof and inherently IP67, the approach of choice for small rugged packs (power sports, marine, tools). Unserviceable by design and heavy per Wh; density shown is the cured potting that dominates the build.',
      dataQuality: 'typical-class',
      material: 'potted',
      densityKgM3: 1450,
      flameRating: 'UL94 V-0',
      ipClass: 'IP67',
    },
    {
      id: 'gfrp-composite-enclosure',
      name: 'GFRP composite enclosure (FR resin)',
      kind: 'composite',
      forms: ['cylindrical', 'prismatic', 'pouch'],
      suppliers: ['SGL Carbon', 'IDI Composites'],
      notes: 'Compression-molded or laid-up glass-fiber composite in a flame-retardant (V-0 capable) resin system; lighter than steel, electrically insulating, and increasingly used for EV pack lids where its burn-through resistance beats thin aluminum. Classed here under plastic-v0 since the FR polymer matrix governs its fire behavior.',
      dataQuality: 'typical-class',
      material: 'plastic-v0',
      densityKgM3: 1900,
      flameRating: 'UL94 V-0',
      ipClass: 'IP67',
    },
  ],
};

// Sensible per-form defaults. Every id exists in COMPONENTS and lists the form
// in its forms array (see verification below componentById).
export const DEFAULTS_BY_FORM = {
  cylindrical: {
    busbar: 'nickel-strip-0p15',
    spacer: 'pp-honeycomb-holder',
    vent: 'cell-score-vent-cid',
    cooling: 'passive-air',
    tim: 'none-dry',
    housing: 'folded-aluminum-sheet',
  },
  prismatic: {
    busbar: 'stamped-aluminum-busbar',
    spacer: 'aerogel-barrier-sheet',
    vent: 'prismatic-burst-disc',
    cooling: 'bottom-cold-plate',
    tim: 'dispensable-gap-filler',
    housing: 'extruded-aluminum-enclosure',
  },
  pouch: {
    busbar: 'pouch-tab-icb',
    spacer: 'compression-foam-pad',
    vent: 'ptfe-breather-membrane',
    cooling: 'bottom-cold-plate',
    tim: 'silicone-gap-pad',
    housing: 'folded-aluminum-sheet',
  },
};

/**
 * Components in a category that are applicable to a cell form factor.
 * @param {string} category one of COMPONENT_CATEGORIES keys
 * @param {'cylindrical'|'prismatic'|'pouch'} form
 * @returns {Array<object>} possibly empty array
 */
export function componentsFor(category, form) {
  const list = COMPONENTS[category];
  if (!list) return [];
  return list.filter((c) => c.forms.includes(form));
}

/**
 * Look up a component by category and id.
 * @param {string} category one of COMPONENT_CATEGORIES keys
 * @param {string} id component id
 * @returns {object|null} the component, or null if missing
 */
export function componentById(category, id) {
  const list = COMPONENTS[category];
  if (!list) return null;
  return list.find((c) => c.id === id) || null;
}
