// prepare.mjs — stage the app for packaging.
//
// The web app has no build step, and adding one for the desktop package would
// be the wrong trade: a bundler is a second thing that can disagree with what
// the page does. So this copies, and nothing else.
//
// It produces one directory, `runner/`, which is both:
//
//   · what the window falls back to if the local compute never starts, and
//   · what `bd.mjs serve` serves, because bd.mjs resolves its root as the
//     parent of its own directory — so `runner/desktop/bd.mjs` sees
//     `runner/` and finds index.html, js/ and vendor/ exactly where it
//     expects them.
//
// One staged copy, used twice, with no path rewriting anywhere.

import { cpSync, mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, statSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const DEFAULT_OUT = path.join(HERE, 'runner');

// Exactly what the application needs at runtime. Tests, tools and the
// contrib data are not shipped — they are how the tool is built, not how it
// is used, and shipping them makes the download bigger for no one's benefit.
export const REQUIRED_RUNTIME_ENTRIES = Object.freeze([
  'index.html',
  'cosim.html',
  'cosim.css',
  'js',
  'knowledge',
  'wasm',
  'vendor',
  'assets',
  'assets3d',
  'profiles',
  'desktop',
  'REFERENCES.md',
  'LICENSE',
  'NOTICE',
]);

// The renderer is generated by the Godot gate, not committed. A source
// checkout remains useful without it, but a release job that has built it
// must carry the exact verified export into the installed application.
export const OPTIONAL_RUNTIME_ENTRIES = Object.freeze(['garage3d/build']);

const bytes = (dir) => readdirSync(dir, { withFileTypes: true }).reduce((sum, e) => {
  const p = path.join(dir, e.name);
  return sum + (e.isDirectory() ? bytes(p) : statSync(p).size);
}, 0);

function assertSafeOutput(output) {
  const resolved = path.resolve(output);
  const filesystemRoot = path.parse(resolved).root;
  const relativeToRepository = path.relative(ROOT, resolved);
  const insideRepository = relativeToRepository === ''
    || (!relativeToRepository.startsWith('..') && !path.isAbsolute(relativeToRepository));
  if (resolved === filesystemRoot || resolved === ROOT || resolved === HERE
      || (insideRepository && resolved !== DEFAULT_OUT)) {
    throw new Error(`prepare: refusing to replace unsafe output directory: ${resolved}`);
  }
  if (existsSync(resolved) && resolved !== DEFAULT_OUT) {
    let marker = null;
    try { marker = JSON.parse(readFileSync(path.join(resolved, 'PACKAGED.json'), 'utf8')); } catch { /* checked below */ }
    if (marker?.packagedFrom !== 'battery-design') {
      throw new Error(`prepare: refusing to replace an existing directory not created by this script: ${resolved}`);
    }
  }
  return resolved;
}

/**
 * Copy the runtime tree without transforming it.
 *
 * `output` is injectable so verification can use a fresh temporary tree
 * instead of deleting or trusting desktop-app/runner from an earlier build.
 */
export function stageApplication({ output = DEFAULT_OUT } = {}) {
  const out = assertSafeOutput(output);
  rmSync(out, { recursive: true, force: true });
  mkdirSync(out, { recursive: true });
  // Mark the directory before copying. If a required copy is interrupted, a
  // later retry can safely replace this partial tree without ever treating an
  // arbitrary existing directory as disposable.
  writeFileSync(path.join(out, 'PACKAGED.json'), JSON.stringify({
    packagedFrom: 'battery-design', staging: true,
  }));

  for (const entry of REQUIRED_RUNTIME_ENTRIES) {
    const from = path.join(ROOT, entry);
    if (!existsSync(from)) {
      throw new Error(`prepare: missing ${entry} — the package would be broken, so this is fatal.`);
    }
    cpSync(from, path.join(out, entry), { recursive: true });
  }

  const optionalIncluded = [];
  for (const entry of OPTIONAL_RUNTIME_ENTRIES) {
    const from = path.join(ROOT, entry);
    if (!existsSync(from)) continue;
    cpSync(from, path.join(out, entry), { recursive: true });
    optionalIncluded.push(entry);
  }

  // The desktop-app directory must not copy itself into itself.
  rmSync(path.join(out, 'desktop', 'node_modules'), { recursive: true, force: true });

  writeFileSync(path.join(out, 'PACKAGED.json'), JSON.stringify({
    packagedFrom: 'battery-design',
    requiredEntries: REQUIRED_RUNTIME_ENTRIES,
    optionalEntriesIncluded: optionalIncluded,
    note: 'Staged by desktop-app/prepare.mjs. No bundler, no transform — these are the same files the web app serves.',
  }, null, 2));

  console.log(`prepare: staged ${REQUIRED_RUNTIME_ENTRIES.length + optionalIncluded.length} entries into ${out} (${(bytes(out) / 1e6).toFixed(1)} MB)`);
  return { output: out, optionalIncluded };
}

function outputFromArgs(argv) {
  const outIndex = argv.indexOf('--out');
  if (outIndex === -1) return process.env.BATTERY_DESIGN_PACKAGE_OUT || DEFAULT_OUT;
  if (!argv[outIndex + 1] || argv[outIndex + 1].startsWith('--')) {
    throw new Error('prepare: --out requires a directory');
  }
  return argv[outIndex + 1];
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    stageApplication({ output: outputFromArgs(process.argv.slice(2)) });
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
